version: '3.1'
networks:
  app-tier:
    driver: overlay
services:
    service1-mongodb:
        image: mymongo:1.0
        networks:
            - app-tier
        ports:
            - "27017:27017"
        volumes:
            - ~/volumes/jhipster/service1/mongodb/:/data/db/
    service1-app:
        image: service1:1.2
        networks:
            - app-tier
        environment:
            - SPRING_PROFILES_ACTIVE=dev,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://service1-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=service1
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080

