version: '2'
services:
    service2-app:
        image: service2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://service2-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=service2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8081:8081
    service2-mongodb:
        extends:
            file: mongodb.yml
            service: service2-mongodb
